POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "type": "OccupationalHealthcare",
  "description": "sadasdd",
  "date": "2020-10-10",
  "specialist": "fdasfd",
  "diagnosisCodes": [
    "M24.2"
  ],
  "healthCheckRating": 0,
  "employerName": "just",
  "sickLeave": {
    "startDate": "2020-10-10",
    "endDate": "2020-10-10"
  }
}